AWSTemplateFormatVersion: 2010-09-09
Description: Creates an S3 bucket and DynamoDB table to use as a Terraform S3 backend.

Parameters:
  StateBucketName:
    Description: Name of the S3 bucket used to store Terraform state files.
    Type: String
    Default: terraform-state
  LockTableName:
    Description: Name of the DynamoDB table used for Terraform state locking.
    Type: String
    Default: terraform-lock
  KMSMasterKeyID:
    Description: ARN of the KMS key used for default S3 object encryption (use default value for AWS managed key).
    Type: String
    Default: AWS managed key
  AppendAccountID:
    Description: Append AWS account ID to resource names.
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'

Conditions:
  UseAWSManagedKey: !Equals [ !Ref KMSMasterKeyID, AWS managed key ]
  AppendAccountID: !Equals [ !Ref AppendAccountID, 'true' ]

Resources:
  StateBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !If [ AppendAccountID, !Join [ '-', [ !Ref StateBucketName, !Ref AWS::AccountId ] ], !Ref StateBucketName ]
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !If [ UseAWSManagedKey, !Ref AWS::NoValue, !Ref KMSMasterKeyID ]
      VersioningConfiguration:
        Status: Enabled

  BucketPolicy:
     Type: AWS::S3::BucketPolicy
     Properties:
       Bucket: !Ref StateBucket
       PolicyDocument:
         Version: 2012-10-17
         Statement:
           - Sid: AllowTLSRequestsOnly
             Principal: '*'
             Action: 's3:*'
             Effect: Deny
             Resource:
               - !GetAtt [ StateBucket, Arn ]
               - !Sub [ '${BucketArn}/*', BucketArn: !GetAtt [ StateBucket, Arn ] ]
             Condition:
               Bool:
                 aws:SecureTransport : false
               NumericLessThan:
                 s3:TlsVersion: 1.2

  LockTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !If [ AppendAccountID, !Join [ '-', [ !Ref LockTableName, !Ref AWS::AccountId ] ], !Ref LockTableName ]
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true

Outputs:
  Bucket:
    Value: !Ref StateBucket
    Description: S3 bucket name
  DynamodbTable:
    Value: !Ref LockTable
    Description: DynamoDB table name
  Region:
    Value: !Ref AWS::Region
    Description: AWS Region
